apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  namespace: roboshop
  labels: # these labels are deployment labels
    app: debug
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: debug
      project: roboshop
  template:
    metadata:
      labels: # these labels are pod labels
        app: debug
        project: roboshop
    spec:
      containers:
      - name: debug
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion}}"
        imagePullPolicy: Always