apiVersion: v1
kind: Service
metadata:
  name: debug
  namespace: roboshop
spec:
  selector:
    app: debug
    project: roboshop
  ports:
  - protocol: TCP
    port: 82 #service-port
    targetPort: 82 #container-port